# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35607e33f777bb45fe69a7ee9a62f0cb34ac59f46cae12d407bc20738ae93871decb6cae80225490df0008a5f9f76c16c5190eed6edc665f359db448ba4c26bb

test:
  secret_key_base: 0ce1a895675b1d8bfa6e2e53255c76dc3b63eba7127c53678f95a4d41683b35f1516aad4e64808944f14d74267cae272daf73b3cd750df274170f3eb00d950ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
